"""DAST checks — each module exports check functions."""
from .headers import (
    check_security_headers,
    check_cache_control,
    check_sri,
    check_version_headers,
    check_coop_coep,
    check_xss_protection_header,
    check_csp_reporting,
    check_expect_ct,
    check_permissions_policy,
    check_content_type_sniffing,
    check_clickjacking,
)
from .ssl import check_ssl_tls, check_http_redirect_https, check_hsts_preload, check_hsts_subdomains
from .cookies import check_cookie_security, check_cookie_prefix
from .recon import (
    check_info_disclosure,
    check_tech_fingerprint,
    check_sitemap_xml,
    check_robots_txt,
    check_directory_listing,
    check_backup_files,
    check_api_docs_exposure,
    check_security_txt,
    check_dotenv_git,
)
from .injection import (
    check_cors,
    check_open_redirect,
    check_host_header_injection,
    check_crlf_injection,
    check_xss_basic,
    check_sqli_error,
)
from .http import (
    check_http_methods,
    check_rate_limiting,
    check_sensitive_data,
    check_form_autocomplete,
    check_debug_response,
)
from .misc import (
    check_weak_referrer,
    check_cache_age,
    check_upgrade_insecure,
    check_redirect_chain,
    check_timing_allow_origin,
    check_alt_svc,
    check_content_disposition,
    check_pragma_no_cache,
    check_server_timing,
    check_via_header,
    check_x_forwarded_disclosure,
    check_allow_dangerous,
    check_corp,
    check_clear_site_data,
    check_trace_xst,
)
from .crypto import check_padding_oracle
from .advanced import (
    check_jwt_security,
    check_csrf_protection,
    check_csp_deep,
    check_path_traversal,
    check_ssrf,
    check_command_injection,
    check_cors_deep,
    check_http_smuggling,
)
from .modern import (
    check_insecure_deserialization,
    check_ssrf_advanced,
    check_broken_access_control,
    check_mass_assignment,
    check_api_security_misconfiguration,
    check_server_side_template_injection,
    check_prototype_pollution,
    check_dns_rebinding,
    check_cache_poisoning,
    check_cors_null_origin,
)
from .exposure import (
    check_cloud_metadata_exposure,
    check_git_exposure,
    check_env_file_exposure,
    check_docker_exposure,
    check_ci_cd_exposure,
    check_secret_in_response,
    check_graphql_introspection,
    check_source_map_exposure,
)
from .network import (
    check_admin_panel_exposure,
    check_database_exposure,
    check_websocket_security,
    check_service_worker_security,
    check_csp_bypass_vectors,
    check_subdomain_takeover,
)

__all__ = [
    "check_security_headers",
    "check_ssl_tls",
    "check_cookie_security",
    "check_cors",
    "check_info_disclosure",
    "check_http_methods",
    "check_tech_fingerprint",
    "check_sitemap_xml",
    "check_robots_txt",
    "check_directory_listing",
    "check_open_redirect",
    "check_rate_limiting",
    "check_xss_basic",
    "check_sqli_error",
    "check_api_docs_exposure",
    "check_host_header_injection",
    "check_crlf_injection",
    "check_sensitive_data",
    "check_sri",
    "check_cache_control",
    "check_form_autocomplete",
    "check_backup_files",
    "check_security_txt",
    "check_http_redirect_https",
    "check_hsts_preload",
    "check_version_headers",
    "check_coop_coep",
    "check_weak_referrer",
    "check_debug_response",
    "check_dotenv_git",
    "check_content_type_sniffing",
    "check_clickjacking",
    "check_trace_xst",
    "check_expect_ct",
    "check_permissions_policy",
    "check_xss_protection_header",
    "check_csp_reporting",
    "check_server_timing",
    "check_via_header",
    "check_x_forwarded_disclosure",
    "check_allow_dangerous",
    "check_corp",
    "check_clear_site_data",
    "check_cache_age",
    "check_upgrade_insecure",
    "check_cookie_prefix",
    "check_redirect_chain",
    "check_timing_allow_origin",
    "check_alt_svc",
    "check_hsts_subdomains",
    "check_content_disposition",
    "check_pragma_no_cache",
    "check_padding_oracle",
    "check_jwt_security",
    "check_csrf_protection",
    "check_csp_deep",
    "check_path_traversal",
    "check_ssrf",
    "check_command_injection",
    "check_cors_deep",
    "check_http_smuggling",
    # Modern OWASP 2021-2025
    "check_insecure_deserialization",
    "check_ssrf_advanced",
    "check_broken_access_control",
    "check_mass_assignment",
    "check_api_security_misconfiguration",
    "check_server_side_template_injection",
    "check_prototype_pollution",
    "check_dns_rebinding",
    "check_cache_poisoning",
    "check_cors_null_origin",
    # Exposure
    "check_cloud_metadata_exposure",
    "check_git_exposure",
    "check_env_file_exposure",
    "check_docker_exposure",
    "check_ci_cd_exposure",
    "check_secret_in_response",
    "check_graphql_introspection",
    "check_source_map_exposure",
    # Network & Infrastructure
    "check_admin_panel_exposure",
    "check_database_exposure",
    "check_websocket_security",
    "check_service_worker_security",
    "check_csp_bypass_vectors",
    "check_subdomain_takeover",
    # Deep protocol checks (Phase 11)
    "check_graphql_deep",
    "check_websocket_deep",
    "check_api_schema",
]

from .graphql import check_graphql_deep
from .websocket import check_websocket_deep
from .api_schema import check_api_schema
